### ISSUE TITLE
How to input two segment images

### ISSUE THREAD

**Issue by panfengli** [liyin2015/superpixel_crfasrnn#2]
Thanks for your work!

I am wondering how to input two segment images, namely the BGPS one and the mean-shift one. In your current code, it seems only one superpixel input is supported.

**Comment by liyin2015** [comment]
try to add another set into the list [img_data, seg_data],
```
probs = model.predict([img_data, seg_data], verbose=False)[0, :, :, :]
```

**Comment by liyin2015** [comment]
Also, I changed the crf models to support flexible set of segmented images. Set the parameters as follows:
```
model = get_crfrnn_model_def(num_segs = 1)
```
The code is not tested yet. Please help check if the code works. Thank you.

**Comment by panfengli** [comment]
Thank you!
